site_name: Cheat Sheets
repo_url: https://github.com/gozeon/cheatsheets
repo_name: gozeon/cheatsheets
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - navigation.footer
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gozeon
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/gozeonl

markdown_extensions:
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - attr_list
  - md_in_html

